### PR TITLE
Use all dependencies from conda-forge

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Review by lezcano — COMMENTED** [review]
This changes the cuda version to 12. Would it also work setting `cuda-version=11.8`?

**Comment by isuruf** [comment]
11.8 already does not work for me due to the channel priority issue. i.e. conda-forge has `cuda-libraries-dev` only for 12.0 and not for 11.8. Therefore, conda/mamba does not find the ones from the `nvidia` label.

**Comment by lezcano** [comment]
Ok, let's update.

I'm not sure about the pip changes though. https://github.com/suo/lintrunner has releases up to 0.10.7, but condaforge advertises version 0.11.0? I'd prefer to keep pulling these from pip, as those are surely up to date. Nothing depends on these, so it's not such a big deal

**Review by lezcano — APPROVED** [review]
Cool. More uniform is better

**Pull request merged**
